---
- name: error handling
  hosts: webserver
  tasks:
   - block:
      - name: install tomcat7
        apt:
         name: tomcat7
         state: present
     rescue: 
      - name: install tomcat8
        apt:
         name: tomcat8
         state: present
     always:
      - name: check url response
        uri:
         url: 172.31.40.145
         status_code: 200
