---
- name: creating loops
  hosts: webserver
  tasks:
   - name: create loop 
     apt:
      name: "{{item.a}}"
      state: "{{item.b}}"
      update_cache: "{{item.c}}"
     with_items:
      - {a: tree,b: present,c: no}
      - {a: maven,b: latest,c: yes}

